name: AWS EC2 and S3 Demo
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  S3buckets:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: myuniquebucket-${{ github.run_id }}
    steps:
      - name: Create a file
        run: echo "Hello from GHA!" > File1.txt
      - name: Create an S3 Bucket
        run: aws s3 mb s3://$BUCKET_NAME
      - name: List all the S3 Buckets
        run: aws s3 ls
      - name: Upload the file to the S3 Bucket
        run: aws s3 cp ./File1.txt s3://$BUCKET_NAME/File1.txt
      - name: Download the file from the S3 Bucket and rename it
        run: aws s3 cp s3://$BUCKET_NAME/File1.txt ./File2.txt
      - name: Show the downloaded file
        run: cat File2.txt

  EC2Instances:
    runs-on: ubuntu-latest
    steps:
      - name: Launch an EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0ff8a91507f77f867 \
            --instance-type t3.micro \
            --security-group-ids sg-024acc3fa5e677c4f
      - name: Describe instances
        run: aws ec2 describe-instances
