name: AWS EC2 and S3 Demo
on:
  workflow_dispatch:

jobs:
  S3buckets:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Create a file
        run: echo "Hello from GHA!" > File1.txt

      - name: Create an S3 Bucket
        run:  aws s3 mb s3://myuniquebucket-${{ github.run_id }} --region $AWS_DEFAULT_REGION

      - name: List all the S3 Buckets
        run: aws s3 ls

      - name: Upload the file to S3 Bucket
        run: aws s3 cp ./File1.txt s3://ghademo

      - name:  Download a file from S3 Bucket and Rename it
        run: aws s3 cp s3://ghademo/NewFile.txt ./File2.txt

  EC2Instances:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}

          aws ec2 run-instances \
            --image-id ami-0ff8a91507f77f867 \
            --instance-type t3.micro \
            --security-group-ids sg-024acc3fa5e677c4f

          aws ec2 describe-instances

        
