# Build on Push
name: Build on Dispatch
on:
  workflow_dispatch:

jobs:
  Build_on_Dispatch:
    name: Trigger the Workflow on Dispatch event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run the tests
        run: pytest
